name: Auto Rebranding ZineROM

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rename-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Replace Text Inside All Files
        run: |
          # تغيير الكلمة الكبيرة
          find . -type f -not -path '*/.*' -exec sed -i 's/QuantumROM/ZineROM/g' {} +
          # تغيير الكلمة الصغيرة (لو موجودة)
          find . -type f -not -path '*/.*' -exec sed -i 's/QuantumRom/ZineRom/g' {} +

      - name: Rename Folders and Scripts
        run: |
          if [ -d "QuantumROM" ]; then
            mv QuantumROM ZineROM
          fi
          if [ -f "scripts/QuantumRom.sh" ]; then
            mv scripts/QuantumRom.sh scripts/ZineRom.sh
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "حذف كوانتم وتغيير اسم التول بالكامل إلى زين روم" || exit 0
          git push

